- hosts: init-master
  remote_user: root
  vars:
    kubeadm_role: init
    kubeadm_cmd: init
  roles:
    - node
    - init

- hosts: masters
  remote_user: root
  vars:
    kubeadm_role: control-plane
    kubeadm_cmd: join
  roles:
    - node

- hosts: workers
  remote_user: root
  vars:
    kubeadm_role: worker
    kubeadm_cmd: join
  roles:
    - node
