- hosts: init-master
  remote_user: root
  vars:
    kubeadm_role: init
  roles:
    - node
    - init

- hosts: masters
  remote_user: root
  vars:
    kubeadm_role: control-plane
  roles:
    - node

- hosts: workers
  remote_user: root
  vars:
    kubeadm_role: worker
  roles:
    - node
