---
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
nodeRegistration:
  name: {{ inventory_hostname }}
controlPlane:
    certificateKey: {{ hostvars[groups['init-master'][0]]['kubeadm_certkey'] }}
discovery:
  bootstrapToken: 
    token: {{ hostvars[groups['init-master'][0]]['kubeadm_token'] }}
    apiServerEndpoint: {{ controlPlaneEndpoint }}:6443
    unsafeSkipCAVerification: true # TODO: figure out how to get the caCertHash
