ansible_port: 2222 
ansible_python_interpreter: "/usr/bin/python3"
ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
ansible_shell_executable: "ctr --namespace services.linuxkit tasks exec --exec-id ansible-kubelet kubelet sh"

# Actual vars start here
clusterName: local
podSubnet: 100.97.0.0/16
serviceSubnet: 100.96.0.0/16
