- name: CHECKING IF NODE HAS CONFIGURATION
  stat:
    path: /var/lib/kubelet/config.yaml
  register: kubelet_config

- name: PLACING KUBEADM CONFIGURATION
  template: 
    src: "kubeadm-{{ kubeadm_role }}.yaml"
    dest: /run/kubeadm.yaml
    owner: root
    group: root
    mode: '0600'
  when: not kubelet_config.stat.exists

- name: TELLING KUBEADM TO RUN
  copy:
    content: ""
    dest: /run/kubeadm-run
    force: no
    owner: root
    group: root
    mode: '0600'
  when: not kubelet_config.stat.exists

- name: WAITING FOR KUBEADM TO FINISH
  wait_for: 
    path: /hostroot/var/log/kubeadm.out.log
    search_regex: "kubeadm has completed"
    msg: kubeadm didn't finish there may be errors in it's logs
  when: not kubelet_config.stat.exists
